//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace App.SQL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ruta
    {
        public string id_ruta { get; set; }
        public string origen_ruta { get; set; }
        public string destino_ruta { get; set; }
        public Nullable<bool> repostar_gasolina { get; set; }
        public Nullable<System.DateTime> fecha_ruta { get; set; }
        public Nullable<System.DateTime> duracion_ruta { get; set; }
        public Nullable<double> precio_repostaje { get; set; }
        public Nullable<double> kms_ruta { get; set; }
    }
}
